version: '2'

services:
    php:
      build:
        dockerfile: ./docker/serverweb/Dockerfile
        context: ./
      ports:
        - "8080:80"
      volumes:
        - ./www:/var/www/site
      privileged: true
      restart: always
