version: '2'

services:

    php:
      build:
        dockerfile: ./docker/serverweb/Dockerfile
        context: ./
      ports:
        - "8080:80"
      volumes:
        - ./www:/web/virtualhosts
      links:
        - db:mariadb
      privileged: true
      restart: always

    db:
        image: mariadb:latest
        ports: 
          - "3307:3306"
        volumes:
          - ./db:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: docker
          MYSQL_DATABASE: mydb
          MYSQL_USER: userdb
          MYSQL_PASSWORD: secret
